// @flow
export const GET_PART_LIST = "GET_PART_LIST";
export const GET_PART_LIST_SUCCESS = "GET_PART_LIST_SUCCESS";
export const GET_PART_LIST_FAILURE = "GET_PART_LIST_FAILURE";

export const ADD_EDIT_PART = "ADD_EDIT_PART";
export const ADD_EDIT_PART_SUCCESS = "ADD_EDIT_PART_SUCCESS";
export const ADD_EDIT_PART_FAILURE = "ADD_EDIT_PART_FAILURE";
